// Various defines used to implement threaded interpretation in the VMs main loop
#ifndef THREADED_CODE_ENABLED

    #define vm_break break
    #define vm_case(opcode) case opcode
    #define vm_switch(val) switch (val)

#else

    // Code in generated_labels is autogenerated by threading.sh
    void *targets[] =
#include "generated_labels.h"

    #define vm_loop \
        opcode = instructions[ip].opcode;\
        target = targets[opcode];\
        goto *target

    #define vm_break \
        ip++;\
        vm_loop

    #define vm_case(opcode) opcode
    #define vm_switch(val) if (true)

    enum Code opcode;
    void *target;
    vm_loop;

#endif
