#!/usr/bin/env bash
str="{ "
count=0
rm -f generated_labels.h
echo "/* Code in this file is autogenerated - do not edit */" >> generated_labels.h
echo "{" >> generated_labels.h
while read -r line; do
    if [[ "$line" == "};" ]]; then
        break
    fi
    if [[ $count -gt 2 ]]; then
        # str+="&&$line"
        echo "&&$line" >> generated_labels.h
    fi
    count=$((count+1))
done < bytecode.h
echo "};" >> generated_labels.h

